"""Create all tables according to ERD

Revision ID: a984eb0e4af2
Revises: 
Create Date: 2026-05-07 15:09:50.039144

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg


# revision identifiers, used by Alembic.
revision = 'a984eb0e4af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(precision=10, decimal_return_scale=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=11, decimal_return_scale=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("location_type IN ('city', 'zip_code', 'coordinates', 'landmark')", name='valid_location_type'),
    sa.CheckConstraint('end_date >= start_date', name='valid_date_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_record_end_date'), 'weather_record', ['end_date'], unique=False)
    op.create_index(op.f('ix_weather_record_id'), 'weather_record', ['id'], unique=False)
    op.create_index(op.f('ix_weather_record_location_name'), 'weather_record', ['location_name'], unique=True)
    op.create_index(op.f('ix_weather_record_start_date'), 'weather_record', ['start_date'], unique=False)
    op.create_table('additional_api_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_record_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weather_record_id'], ['weather_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_api_data_id'), 'additional_api_data', ['id'], unique=False)
    op.create_index(op.f('ix_additional_api_data_weather_record_id'), 'additional_api_data', ['weather_record_id'], unique=False)
    op.create_table('map_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_record_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('static_map_url', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(precision=10, decimal_return_scale=8), nullable=True),
    sa.Column('lng', sa.Float(precision=11, decimal_return_scale=8), nullable=True),
    sa.Column('place_type', sa.String(length=50), nullable=True),
    sa.Column('point_of_interest', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weather_record_id'], ['weather_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_location_id'), 'map_location', ['id'], unique=False)
    op.create_index(op.f('ix_map_location_weather_record_id'), 'map_location', ['weather_record_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_record_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('temperature', sa.Float(precision=5, decimal_return_scale=2), nullable=True),
    sa.Column('feels_like', sa.Float(precision=5, decimal_return_scale=2), nullable=True),
    sa.Column('temp_min', sa.Float(precision=5, decimal_return_scale=2), nullable=True),
    sa.Column('temp_max', sa.Float(precision=5, decimal_return_scale=2), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(precision=5, decimal_return_scale=2), nullable=True),
    sa.Column('weather_description', sa.String(length=100), nullable=True),
    sa.Column('icon_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weather_record_id'], ['weather_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_record_id', 'forecast_date', name='uq_record_forecast_date')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_weather_record_id'), 'weather_data', ['weather_record_id'], unique=False)
    op.create_table('youtube_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_record_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weather_record_id'], ['weather_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_video_id'), 'youtube_video', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_video_weather_record_id'), 'youtube_video', ['weather_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_video_weather_record_id'), table_name='youtube_video')
    op.drop_index(op.f('ix_youtube_video_id'), table_name='youtube_video')
    op.drop_table('youtube_video')
    op.drop_index(op.f('ix_weather_data_weather_record_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_map_location_weather_record_id'), table_name='map_location')
    op.drop_index(op.f('ix_map_location_id'), table_name='map_location')
    op.drop_table('map_location')
    op.drop_index(op.f('ix_additional_api_data_weather_record_id'), table_name='additional_api_data')
    op.drop_index(op.f('ix_additional_api_data_id'), table_name='additional_api_data')
    op.drop_table('additional_api_data')
    op.drop_index(op.f('ix_weather_record_start_date'), table_name='weather_record')
    op.drop_index(op.f('ix_weather_record_location_name'), table_name='weather_record')
    op.drop_index(op.f('ix_weather_record_id'), table_name='weather_record')
    op.drop_index(op.f('ix_weather_record_end_date'), table_name='weather_record')
    op.drop_table('weather_record')
    # ### end Alembic commands ###
